---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: langclient-techlauncharizona
  namespace: chatur
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: langclient-techlauncharizona
  strategy:
    rollingUpdate:
      maxSurge: 200%
  template:
    metadata:
      labels:
        app.kubernetes.io/name: langclient-techlauncharizona
    spec:
      volumes:
      - name: vectordb
        emptyDir:
          sizeLimit: 10Gi
      - name: llm-model
        emptyDir:
          sizeLimit: 10Gi
      restartPolicy: Always
      initContainers:
      - name: stage-vectordb
        image: harbor.cyverse.org/ai/ragcopy:0.0.2
        args:
        - "--src"
        - "/iplant/home/shared/chatur/vectordb"
        - "--dest"
        - "/vectordb"
        resources:
          requests:
            cpu: "100m"
            memory: "5Gi"
            ephemeral-storage: "15Gi"
          limits:
            cpu: "100m"
            memory: "5Gi"
            ephemeral-storage: "15Gi"
        volumeMounts:
        - name: vectordb
          mountPath: "/vectordb"
      containers:
      - name: langclient
        image: harbor.cyverse.org/ai/langclient:0.0.6
        command:
        - "python3"
        - "/opt/langserve/langclient.py"
        args:
        - "0.0.0.0"
        - "80"
        - "/vectordb/RNR355"
        - "langchain"
        - "ollama"
        - "mistral"
        resources:
          requests:
            cpu: "200m"
            memory: "10Gi"
            ephemeral-storage: "20Gi"
          limits:
            cpu: "1"
            memory: "10Gi"
            ephemeral-storage: "20Gi"
        ports:
        - name: listen-port
          containerPort: 80
        livenessProbe:
          httpGet:
            path: /docs
            port: 80
          failureThreshold: 1
          timeoutSeconds: 5
          periodSeconds: 10
        startupProbe:
          httpGet:
            path: /docs
            port: 80
          failureThreshold: 10
          timeoutSeconds: 5
          periodSeconds: 10
        volumeMounts:
        - name: vectordb
          mountPath: "/vectordb"
---
apiVersion: v1
kind: Service
metadata:
  name: langclient-techlauncharizona
  namespace: chatur
spec:
  selector:
    app.kubernetes.io/name: langclient-techlauncharizona
  ports:
    - protocol: TCP
      port: 80
      targetPort: listen-port
